/*
    *************
        Creates triggers that adds new and updated records from the raw catch data staging table (raw_catch_data_staging_table) to
        the full raw catch data table (raw_catch_data) and the reduced column count catch table (reduced_catch_data) after insert, before clearing the staging table.
    *************
*/


CREATE OR REPLACE FUNCTION propagate_data_to_reduced_catch_data_table()
    RETURNS TRIGGER AS
$BODY$
BEGIN
    /*
    *************
        Insert new records.
    *************
    */
    INSERT INTO fangstanalyse.public.reduced_catch_data(rundvekt,
                                                        fangstfelt,
                                                        art_kode,
                                                        epoch_landing,
                                                        timestamp_landing,
                                                        lengdekode,
                                                        kvalitetkode,
                                                        redskap_kode,
                                                        dokument_versjonsnummer,
                                                        dokument_versjonstidspunkt,
                                                        dokumentnummer,
                                                        linjenummer,
                                                        fartoy_navn,
                                                        fartoy_kommune,
                                                        art,
                                                        kvalitet,
                                                        redskap,
                                                        lengdegruppe,
                                                        year,
                                                        month,
                                                        year_and_month)
    VALUES (COALESCE(new.rundvekt, 0),
            CASE
                WHEN new.lok != '0000'
                    AND new.lok != '9999' THEN new.lok
                WHEN new.fangstfelt_kode != 0 THEN
                    CASE
                        WHEN new.fangstfelt_kode > 9999 THEN SUBSTR(CAST(new.fangstfelt_kode AS TEXT), 2)
                        ELSE '9999'
                        END
                ELSE '9999'
                END,
            COALESCE(CAST(new.artfdir_kode AS integer), 0),
            EXTRACT(epoch from to_timestamp(CONCAT(new.landingsdato, new.landingsklokkeslett), 'dd.MM.YYYYHH24:MI:SS')),
            TO_TIMESTAMP(CONCAT(new.landingsdato, new.landingsklokkeslett), 'dd.MM.YYYYHH24:MI:SS'),
            COALESCE(CAST(new.lengdegruppe_kode AS integer), 0),
            COALESCE(CAST(new.kvalitet_kode AS integer), 0),
            COALESCE(CAST(new.redskapgruppe_kode AS integer), 0),
            COALESCE(CAST(new.dokument_versjonsnummer AS integer), 0),
            COALESCE(new.dokument_versjonstidspunkt, ''),
            COALESCE(new.dokumentnummer, 0),
            COALESCE(CAST(new.linjenummer AS integer), 0),
            COALESCE(new.fartøynavn, ''),
            COALESCE(new.fartøykommune, ''),
            COALESCE(new.artfdir, ''),
            COALESCE(new.kvalitet, ''),
            COALESCE(new.redskap, ''),
            COALESCE(new.lengdegruppe, ''),
            EXTRACT(YEAR from to_timestamp(CONCAT(new.landingsdato, new.landingsklokkeslett), 'dd.MM.YYYYHH24:MI:SS')),
            EXTRACT(MONTH from to_timestamp(CONCAT(new.landingsdato, new.landingsklokkeslett), 'dd.MM.YYYYHH24:MI:SS')),
            CONCAT(EXTRACT(YEAR from to_timestamp(CONCAT(new.landingsdato, new.landingsklokkeslett), 'dd.MM.YYYYHH24:MI:SS')), '-',
                   EXTRACT(MONTH from to_timestamp(CONCAT(new.landingsdato, new.landingsklokkeslett), 'dd.MM.YYYYHH24:MI:SS'))))
    ON CONFLICT (dokumentnummer, linjenummer)
        DO UPDATE
        SET rundvekt                   = excluded.rundvekt,
            fangstfelt                 = excluded.fangstfelt,
            art_kode                   = excluded.art_kode,
            epoch_landing              = excluded.epoch_landing,
            lengdekode                 = excluded.lengdekode,
            kvalitetkode               = excluded.kvalitetkode,
            redskap_kode               = excluded.redskap_kode,
            dokument_versjonsnummer    = excluded.dokument_versjonsnummer,
            dokument_versjonstidspunkt = excluded.dokument_versjonstidspunkt,
            dokumentnummer             = excluded.dokumentnummer,
            linjenummer                = excluded.linjenummer,
            fartoy_navn                = excluded.fartoy_navn,
            fartoy_kommune             = excluded.fartoy_kommune,
            art                        = excluded.art,
            kvalitet                   = excluded.kvalitet,
            redskap                    = excluded.redskap,
            lengdegruppe               = excluded.lengdegruppe,
            year                       = excluded.year,
            month                      = excluded.month,
            year_and_month             = excluded.year_and_month;

    RETURN NEW;
END;
$BODY$
    language plpgsql;

CREATE OR REPLACE FUNCTION add_new_data_to_raw_catch_data_table()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    INSERT INTO public.raw_catch_data AS target(dokumentnummer,
                                                dokumenttype_kode,
                                                dokumenttype,
                                                dokument_versjonsnummer,
                                                dokument_salgsdato,
                                                dokument_versjonstidspunkt,
                                                salgslag_id,
                                                salgslag_kode,
                                                salgslag,
                                                mottaker_id,
                                                mottakernasjonalitet_kode,
                                                mottakernasjonalitet,
                                                mottaksstasjon,
                                                landingskommune_kode,
                                                landingskommune,
                                                landingsfylke_kode,
                                                landingsfylke,
                                                landingsnasjon_kode,
                                                landingsnasjon,
                                                produksjonsanlegg,
                                                produksjonskommune_kode,
                                                produksjonskommune,
                                                "mottakende_fartøy_reg.merke",
                                                mottakende_fartøy_rkal,
                                                mottakende_fartøytype_kode,
                                                "mottakende_fart.type",
                                                "mottakende_fartøynasj._kode",
                                                "mottakende_fart.nasj",
                                                fisker_id,
                                                fiskerkommune_kode,
                                                fiskerkommune,
                                                fiskernasjonalitet_kode,
                                                fiskernasjonalitet,
                                                fartøy_id,
                                                registreringsmerke_seddel,
                                                radiokallesignal_seddel,
                                                fartøynavn,
                                                fartøytype_kode,
                                                fartøytype,
                                                "kvotefartøy_reg.merke",
                                                besetning,
                                                fartøykommune_kode,
                                                fartøykommune,
                                                fartøyfylke_kode,
                                                fartøyfylke,
                                                fartøynasjonalitet_kode,
                                                fartøynasjonalitet,
                                                fartøynasjonalitet_gruppe,
                                                største_lengde,
                                                lengdegruppe_kode,
                                                lengdegruppe,
                                                bruttotonnasje_1969,
                                                bruttotonnasje_annen,
                                                byggeår,
                                                ombyggingsår,
                                                motorkraft,
                                                motorbyggeår,
                                                fangstår,
                                                siste_fangstdato,
                                                kvotetype_kode,
                                                kvotetype,
                                                redskap_kode,
                                                redskap,
                                                redskapgruppe_kode,
                                                redskapgruppe,
                                                redskaphovedgruppe_kode,
                                                redskaphovedgruppe,
                                                fangstfelt_kode,
                                                "kyst/hav_kode",
                                                hovedområde_kode,
                                                hovedområde,
                                                lon_hovedområde,
                                                lat_hovedområde,
                                                lokasjon_kode,
                                                lon_lokasjon,
                                                lat_lokasjon,
                                                sone_kode,
                                                sone,
                                                områdegruppering_kode,
                                                områdegruppering,
                                                hovedområde_fao_kode,
                                                hovedområde_fao,
                                                "nord/sør_for_62_grader_nord",
                                                fangstdagbok_nummer,
                                                fangstdagbok_turnummer,
                                                landingsdato,
                                                landingsklokkeslett,
                                                landingsmåned_kode,
                                                landingsmåned,
                                                landingstidspunkt,
                                                dellanding_signal,
                                                neste_mottaksstasjon,
                                                forrige_mottakstasjon,
                                                linjenummer,
                                                artfdir_kode,
                                                artfdir,
                                                art_kode,
                                                art,
                                                artgruppe_kode,
                                                artgruppe,
                                                arthovedgruppe_kode,
                                                arthovedgruppe,
                                                art_fao_kode,
                                                art_fao,
                                                produkttilstand_kode,
                                                produkttilstand,
                                                konserveringsmåte_kode,
                                                konserveringsmåte,
                                                landingsmåte_kode,
                                                landingsmåte,
                                                kvalitet_kode,
                                                kvalitet,
                                                størrelsesgruppering_kode,
                                                anvendelse_kode,
                                                anvendelse,
                                                anvendelse_hovedgruppe_kode,
                                                anvendelse_hovedgruppe,
                                                antall_stykk,
                                                bruttovekt,
                                                produktvekt,
                                                produktvekt_over_kvote,
                                                rundvekt_over_kvote,
                                                rundvekt,
                                                enhetspris_for_kjøper,
                                                beløp_for_kjøper,
                                                enhetspris_for_fisker,
                                                beløp_for_fisker,
                                                støttebeløp,
                                                lagsavgift,
                                                inndradd_fangstverdi,
                                                etterbetaling,
                                                fangstverdi,
                                                oppdateringstidspunkt,
                                                lok)
    VALUES (NEW.dokumentnummer,
            new.dokumenttype_kode,
            new.dokumenttype,
            new.dokument_versjonsnummer,
            new.dokument_salgsdato,
            new.dokument_versjonstidspunkt,
            new.salgslag_id,
            new.salgslag_kode,
            new.salgslag,
            new.mottaker_id,
            new.mottakernasjonalitet_kode,
            new.mottakernasjonalitet,
            new.mottaksstasjon,
            new.landingskommune_kode,
            new.landingskommune,
            new.landingsfylke_kode,
            new.landingsfylke,
            new.landingsnasjon_kode,
            new.landingsnasjon,
            new.produksjonsanlegg,
            new.produksjonskommune_kode,
            new.produksjonskommune,
            new."mottakende_fartøy_reg.merke",
            new.mottakende_fartøy_rkal,
            new.mottakende_fartøytype_kode,
            new."mottakende_fart.type",
            new."mottakende_fartøynasj._kode",
            new."mottakende_fart.nasj",
            new.fisker_id,
            new.fiskerkommune_kode,
            new.fiskerkommune,
            new.fiskernasjonalitet_kode,
            new.fiskernasjonalitet,
            new.fartøy_id,
            new.registreringsmerke_seddel,
            new.radiokallesignal_seddel,
            new.fartøynavn,
            new.fartøytype_kode,
            new.fartøytype,
            new."kvotefartøy_reg.merke",
            new.besetning,
            new.fartøykommune_kode,
            new.fartøykommune,
            new.fartøyfylke_kode,
            new.fartøyfylke,
            new.fartøynasjonalitet_kode,
            new.fartøynasjonalitet,
            new.fartøynasjonalitet_gruppe,
            new.største_lengde,
            new.lengdegruppe_kode,
            new.lengdegruppe,
            new.bruttotonnasje_1969,
            new.bruttotonnasje_annen,
            new.byggeår,
            new.ombyggingsår,
            new.motorkraft,
            new.motorbyggeår,
            new.fangstår,
            new.siste_fangstdato,
            new.kvotetype_kode,
            new.kvotetype,
            new.redskap_kode,
            new.redskap,
            new.redskapgruppe_kode,
            new.redskapgruppe,
            new.redskaphovedgruppe_kode,
            new.redskaphovedgruppe,
            new.fangstfelt_kode,
            new."kyst/hav_kode",
            new.hovedområde_kode,
            new.hovedområde,
            new.lon_hovedområde,
            new.lat_hovedområde,
            new.lokasjon_kode,
            new.lon_lokasjon,
            new.lat_lokasjon,
            new.sone_kode,
            new.sone,
            new.områdegruppering_kode,
            new.områdegruppering,
            new.hovedområde_fao_kode,
            new.hovedområde_fao,
            new."nord/sør_for_62_grader_nord",
            new.fangstdagbok_nummer,
            new.fangstdagbok_turnummer,
            new.landingsdato,
            new.landingsklokkeslett,
            new.landingsmåned_kode,
            new.landingsmåned,
            new.landingstidspunkt,
            new.dellanding_signal,
            new.neste_mottaksstasjon,
            new.forrige_mottakstasjon,
            new.linjenummer,
            new.artfdir_kode,
            new.artfdir,
            new.art_kode,
            new.art,
            new.artgruppe_kode,
            new.artgruppe,
            new.arthovedgruppe_kode,
            new.arthovedgruppe,
            new.art_fao_kode,
            new.art_fao,
            new.produkttilstand_kode,
            new.produkttilstand,
            new.konserveringsmåte_kode,
            new.konserveringsmåte,
            new.landingsmåte_kode,
            new.landingsmåte,
            new.kvalitet_kode,
            new.kvalitet,
            new.størrelsesgruppering_kode,
            new.anvendelse_kode,
            new.anvendelse,
            new.anvendelse_hovedgruppe_kode,
            new.anvendelse_hovedgruppe,
            new.antall_stykk,
            new.bruttovekt,
            new.produktvekt,
            new.produktvekt_over_kvote,
            new.rundvekt_over_kvote,
            new.rundvekt,
            new.enhetspris_for_kjøper,
            new.beløp_for_kjøper,
            new.enhetspris_for_fisker,
            new.beløp_for_fisker,
            new.støttebeløp,
            new.lagsavgift,
            new.inndradd_fangstverdi,
            new.etterbetaling,
            new.fangstverdi,
            new.oppdateringstidspunkt,
            new.lok)
    ON CONFLICT (dokumentnummer, linjenummer)
        DO UPDATE
        SET dokumentnummer                = excluded.dokumentnummer,
            dokumenttype_kode             = excluded.dokumenttype_kode,
            dokumenttype                  = excluded.dokumenttype,
            dokument_versjonsnummer       = excluded.dokument_versjonsnummer,
            dokument_salgsdato            = excluded.dokument_salgsdato,
            dokument_versjonstidspunkt    = excluded.dokument_versjonstidspunkt,
            salgslag_id                   = excluded.salgslag_id,
            salgslag_kode                 = excluded.salgslag_kode,
            salgslag                      = excluded.salgslag,
            mottaker_id                   = excluded.mottaker_id,
            mottakernasjonalitet_kode     = excluded.mottakernasjonalitet_kode,
            mottakernasjonalitet          = excluded.mottakernasjonalitet,
            mottaksstasjon                = excluded.mottaksstasjon,
            landingskommune_kode          = excluded.landingskommune_kode,
            landingskommune               = excluded.landingskommune,
            landingsfylke_kode            = excluded.landingsfylke_kode,
            landingsfylke                 = excluded.landingsfylke,
            landingsnasjon_kode           = excluded.landingsnasjon_kode,
            landingsnasjon                = excluded.landingsnasjon,
            produksjonsanlegg             = excluded.produksjonsanlegg,
            produksjonskommune_kode       = excluded.produksjonskommune_kode,
            produksjonskommune            = excluded.produksjonskommune,
            "mottakende_fartøy_reg.merke" = excluded."mottakende_fartøy_reg.merke",
            mottakende_fartøy_rkal        = excluded.mottakende_fartøy_rkal,
            mottakende_fartøytype_kode    = excluded.mottakende_fartøytype_kode,
            "mottakende_fart.type"        = excluded."mottakende_fart.type",
            "mottakende_fartøynasj._kode" = excluded."mottakende_fartøynasj._kode",
            "mottakende_fart.nasj"        = excluded."mottakende_fart.nasj",
            fisker_id                     = excluded.fisker_id,
            fiskerkommune_kode            = excluded.fiskerkommune_kode,
            fiskerkommune                 = excluded.fiskerkommune,
            fiskernasjonalitet_kode       = excluded.fiskernasjonalitet_kode,
            fiskernasjonalitet            = excluded.fiskernasjonalitet,
            fartøy_id                     = excluded.fartøy_id,
            registreringsmerke_seddel     = excluded.registreringsmerke_seddel,
            radiokallesignal_seddel       = excluded.radiokallesignal_seddel,
            fartøynavn                    = excluded.fartøynavn,
            fartøytype_kode               = excluded.fartøytype_kode,
            fartøytype                    = excluded.fartøytype,
            "kvotefartøy_reg.merke"       = excluded."kvotefartøy_reg.merke",
            besetning                     = excluded.besetning,
            fartøykommune_kode            = excluded.fartøykommune_kode,
            fartøykommune                 = excluded.fartøykommune,
            fartøyfylke_kode              = excluded.fartøyfylke_kode,
            fartøyfylke                   = excluded.fartøyfylke,
            fartøynasjonalitet_kode       = excluded.fartøynasjonalitet_kode,
            fartøynasjonalitet            = excluded.fartøynasjonalitet,
            fartøynasjonalitet_gruppe     = excluded.fartøynasjonalitet_gruppe,
            største_lengde                = excluded.største_lengde,
            lengdegruppe_kode             = excluded.lengdegruppe_kode,
            lengdegruppe                  = excluded.lengdegruppe,
            bruttotonnasje_1969           = excluded.bruttotonnasje_1969,
            bruttotonnasje_annen          = excluded.bruttotonnasje_annen,
            byggeår                       = excluded.byggeår,
            ombyggingsår                  = excluded.ombyggingsår,
            motorkraft                    = excluded.motorkraft,
            motorbyggeår                  = excluded.motorbyggeår,
            fangstår                      = excluded.fangstår,
            siste_fangstdato              = excluded.siste_fangstdato,
            kvotetype_kode                = excluded.kvotetype_kode,
            kvotetype                     = excluded.kvotetype,
            redskap_kode                  = excluded.redskap_kode,
            redskap                       = excluded.redskap,
            redskapgruppe_kode            = excluded.redskapgruppe_kode,
            redskapgruppe                 = excluded.redskapgruppe,
            redskaphovedgruppe_kode       = excluded.redskaphovedgruppe_kode,
            redskaphovedgruppe            = excluded.redskaphovedgruppe,
            fangstfelt_kode               = excluded.fangstfelt_kode,
            "kyst/hav_kode"               = excluded."kyst/hav_kode",
            hovedområde_kode              = excluded.hovedområde_kode,
            hovedområde                   = excluded.hovedområde,
            lon_hovedområde               = excluded.lon_hovedområde,
            lat_hovedområde               = excluded.lat_hovedområde,
            lokasjon_kode                 = excluded.lokasjon_kode,
            lon_lokasjon                  = excluded.lon_lokasjon,
            lat_lokasjon                  = excluded.lat_lokasjon,
            sone_kode                     = excluded.sone_kode,
            sone                          = excluded.sone,
            områdegruppering_kode         = excluded.områdegruppering_kode,
            områdegruppering              = excluded.områdegruppering,
            hovedområde_fao_kode          = excluded.hovedområde_fao_kode,
            hovedområde_fao               = excluded.hovedområde_fao,
            "nord/sør_for_62_grader_nord" = excluded."nord/sør_for_62_grader_nord",
            fangstdagbok_nummer           = excluded.fangstdagbok_nummer,
            fangstdagbok_turnummer        = excluded.fangstdagbok_turnummer,
            landingsdato                  = excluded.landingsdato,
            landingsklokkeslett           = excluded.landingsklokkeslett,
            landingsmåned_kode            = excluded.landingsmåned_kode,
            landingsmåned                 = excluded.landingsmåned,
            landingstidspunkt             = excluded.landingstidspunkt,
            dellanding_signal             = excluded.dellanding_signal,
            neste_mottaksstasjon          = excluded.neste_mottaksstasjon,
            forrige_mottakstasjon         = excluded.forrige_mottakstasjon,
            linjenummer                   = excluded.linjenummer,
            artfdir_kode                  = excluded.artfdir_kode,
            artfdir                       = excluded.artfdir,
            art_kode                      = excluded.art_kode,
            art                           = excluded.art,
            artgruppe_kode                = excluded.artgruppe_kode,
            artgruppe                     = excluded.artgruppe,
            arthovedgruppe_kode           = excluded.arthovedgruppe_kode,
            arthovedgruppe                = excluded.arthovedgruppe,
            art_fao_kode                  = excluded.art_fao_kode,
            art_fao                       = excluded.art_fao,
            produkttilstand_kode          = excluded.produkttilstand_kode,
            produkttilstand               = excluded.produkttilstand,
            konserveringsmåte_kode        = excluded.konserveringsmåte_kode,
            konserveringsmåte             = excluded.konserveringsmåte,
            landingsmåte_kode             = excluded.landingsmåte_kode,
            landingsmåte                  = excluded.landingsmåte,
            kvalitet_kode                 = excluded.kvalitet_kode,
            kvalitet                      = excluded.kvalitet,
            størrelsesgruppering_kode     = excluded.størrelsesgruppering_kode,
            anvendelse_kode               = excluded.anvendelse_kode,
            anvendelse                    = excluded.anvendelse,
            anvendelse_hovedgruppe_kode   = excluded.anvendelse_hovedgruppe_kode,
            anvendelse_hovedgruppe        = excluded.anvendelse_hovedgruppe,
            antall_stykk                  = excluded.antall_stykk,
            bruttovekt                    = excluded.bruttovekt,
            produktvekt                   = excluded.produktvekt,
            produktvekt_over_kvote        = excluded.produktvekt_over_kvote,
            rundvekt_over_kvote           = excluded.rundvekt_over_kvote,
            rundvekt                      = excluded.rundvekt,
            enhetspris_for_kjøper         = excluded.enhetspris_for_kjøper,
            beløp_for_kjøper              = excluded.beløp_for_kjøper,
            enhetspris_for_fisker         = excluded.enhetspris_for_fisker,
            beløp_for_fisker              = excluded.beløp_for_fisker,
            støttebeløp                   = excluded.støttebeløp,
            lagsavgift                    = excluded.lagsavgift,
            inndradd_fangstverdi          = excluded.inndradd_fangstverdi,
            etterbetaling                 = excluded.etterbetaling,
            fangstverdi                   = excluded.fangstverdi,
            oppdateringstidspunkt         = excluded.oppdateringstidspunkt,
            lok                           = excluded.lok
    WHERE excluded.dokument_salgsdato IS NOT NULL
      AND excluded.dokument_versjonsnummer > target.dokument_versjonsnummer;

    -- Clear staging table after inserting new and updated data to raw data table
--     DELETE
--     FROM fangstanalyse.public.raw_catch_data_staging_table
--     WHERE 1 = 1;

    RETURN NEW;
END;
$$;


/*
*************
    Create the triggers.
*************
*/

--  Prevents reduntant updates on raw data table and staging table
DROP TRIGGER IF EXISTS suppress_redundant_raw_updates ON fangstanalyse.public.raw_catch_data;
CREATE TRIGGER suppress_redundant_raw_updates
    BEFORE UPDATE
    ON
        fangstanalyse.public.raw_catch_data
    FOR EACH ROW
EXECUTE FUNCTION suppress_redundant_updates_trigger();

-- Updates record if it already exists and there is newer data in the inserted record.
DROP TRIGGER IF EXISTS raw_catch_data_upsert_trigger ON fangstanalyse.public.raw_catch_data_staging_table;
CREATE TRIGGER raw_catch_data_upsert_trigger
    AFTER INSERT
    ON
        fangstanalyse.public.raw_catch_data_staging_table
    FOR EACH ROW
EXECUTE PROCEDURE add_new_data_to_raw_catch_data_table();

--  Apply updates and new records in raw data table to reduced table.
DROP TRIGGER IF EXISTS propagate_changes_on_raw_catch_data_insert_trigger ON fangstanalyse.public.raw_catch_data;
CREATE TRIGGER propagate_changes_on_raw_catch_data_insert_trigger
    AFTER UPDATE OR INSERT
    ON
        fangstanalyse.public.raw_catch_data
    FOR EACH ROW
EXECUTE PROCEDURE propagate_data_to_reduced_catch_data_table();