version: "3.9"

services:
  client:
    image: fhf-datafangst/fhf-datafangst-client:latest
    build:
      dockerfile: dockerfiles/fhf-datafangst-client/Dockerfile
      context: .
    container_name: fhf-datafangst-client
    ports:
      - 11000:80
