name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  cache:
    uses: orcalabs/github-actions/.github/workflows/npm_cache.yml@master
    with:
      src-dir: fhf-datafangst-client

  images:
    uses: orcalabs/github-actions/.github/workflows/images.yml@master
    secrets: inherit
    with:
      keys: |
        fhf-datafangst-client
      object: '{
           "fhf-datafangst-client" : {
              "aks-path" : "apps/base/fhf-datafangst",
              "dockerfile" : "dockerfiles/fhf-datafangst-client/Dockerfile",
              "registry" : "ghcr.io/orcalabs/fhf-datafangst/fhf-datafangst-client"
           }
        }'
  deploy:
    runs-on: ubuntu-latest
    needs: images
    steps:
     - name: Log in to Azure
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: Login to Github container registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Deploy fhf-datafangst-client
       uses: azure/container-apps-deploy-action@v1
       with:
         containerAppName: dev-fhf-datafangst-client
         containerAppEnvironment: dev-kyogre
         resourceGroup: dev
         imageToDeploy: ghcr.io/orcalabs/fhf-datafangst/fhf-datafangst-client:${{ github.sha }}
