name: Check

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master

jobs:
  check-client:
    uses: orcalabs/github-actions/.github/workflows/npm_check.yml@master
    with:
      src-dir: fhf-datafangst-client

  check-fuel-registration:
    uses: orcalabs/github-actions/.github/workflows/npm_check.yml@master
    with:
      src-dir: fhf-datafangst-fuel-registration
      tsconfig: tsconfig.app.json
